//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pustakalay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public BookInfo()
        {
            this.Books = new HashSet<Book>();
        }
    
        public string Title { get; set; }
        public long Isbn { get; set; }
        public int AuthorId { get; set; }
        public int PublisherId { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
